//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mhy16
{
    [Serializable]
    public class LabelPCLMsg : Message
    {
        public const string k_RosMessageName = "mhy16/LabelPCL";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public Sensor.PointCloud2Msg point_cloud;

        public LabelPCLMsg()
        {
            this.name = "";
            this.point_cloud = new Sensor.PointCloud2Msg();
        }

        public LabelPCLMsg(string name, Sensor.PointCloud2Msg point_cloud)
        {
            this.name = name;
            this.point_cloud = point_cloud;
        }

        public static LabelPCLMsg Deserialize(MessageDeserializer deserializer) => new LabelPCLMsg(deserializer);

        private LabelPCLMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            this.point_cloud = Sensor.PointCloud2Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.point_cloud);
        }

        public override string ToString()
        {
            return "LabelPCLMsg: " +
            "\nname: " + name.ToString() +
            "\npoint_cloud: " + point_cloud.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
