//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomInterfaces
{
    [Serializable]
    public class InstanceMsg : Message
    {
        public const string k_RosMessageName = "custom_interfaces/Instance";
        public override string RosMessageName => k_RosMessageName;

        public sbyte label;
        public sbyte instance;

        public InstanceMsg()
        {
            this.label = 0;
            this.instance = 0;
        }

        public InstanceMsg(sbyte label, sbyte instance)
        {
            this.label = label;
            this.instance = instance;
        }

        public static InstanceMsg Deserialize(MessageDeserializer deserializer) => new InstanceMsg(deserializer);

        private InstanceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.label);
            deserializer.Read(out this.instance);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.label);
            serializer.Write(this.instance);
        }

        public override string ToString()
        {
            return "InstanceMsg: " +
            "\nlabel: " + label.ToString() +
            "\ninstance: " + instance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
