//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomInterfaces
{
    [Serializable]
    public class NumMsg : Message
    {
        public const string k_RosMessageName = "custom_interfaces/Num";
        public override string RosMessageName => k_RosMessageName;

        public long num;
        public string name;

        public NumMsg()
        {
            this.num = 0;
            this.name = "";
        }

        public NumMsg(long num, string name)
        {
            this.num = num;
            this.name = name;
        }

        public static NumMsg Deserialize(MessageDeserializer deserializer) => new NumMsg(deserializer);

        private NumMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.num);
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.num);
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "NumMsg: " +
            "\nnum: " + num.ToString() +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
