//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomInterfaces
{
    [Serializable]
    public class TransformationMsg : Message
    {
        public const string k_RosMessageName = "custom_interfaces/Transformation";
        public override string RosMessageName => k_RosMessageName;

        public int idto;
        public int idfrom;
        public Geometry.TwistMsg tf;

        public TransformationMsg()
        {
            this.idto = 0;
            this.idfrom = 0;
            this.tf = new Geometry.TwistMsg();
        }

        public TransformationMsg(int idto, int idfrom, Geometry.TwistMsg tf)
        {
            this.idto = idto;
            this.idfrom = idfrom;
            this.tf = tf;
        }

        public static TransformationMsg Deserialize(MessageDeserializer deserializer) => new TransformationMsg(deserializer);

        private TransformationMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.idto);
            deserializer.Read(out this.idfrom);
            this.tf = Geometry.TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.idto);
            serializer.Write(this.idfrom);
            serializer.Write(this.tf);
        }

        public override string ToString()
        {
            return "TransformationMsg: " +
            "\nidto: " + idto.ToString() +
            "\nidfrom: " + idfrom.ToString() +
            "\ntf: " + tf.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
